/**
 *  Copyright 2019 LinkedIn Corporation. All rights reserved.
 *  Licensed under the BSD 2-Clause License. See the LICENSE file in the project root for license information.
 *  See the NOTICE file in the project root for additional information regarding copyright ownership.
 */
/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.datastream.common;

/**
 * Represents the different types of data change operations.
 */
@SuppressWarnings("all")
public enum EventOperation {
  /**
   * A new record is inserted.
   */
  INSERT,

  /**
   * An existing record is updated.
   */
  UPDATE,

  /**
   * An existing record is deleted.
   */
  DELETE,

  /**
   * A system-related change is performed.
   */
  SYSTEM
}
