package com.linkedin.datastream.connectors.oracle.triggerbased;

import org.apache.avro.Schema;

public class MockSchema {
  //CHECKSTYLE:OFF
  public static final Schema GENERIC_SCHEMA = Schema.parse("{\"name\":\"DaftPunk_Songs\",\"doc\":\"Auto-generatedAvroschemaformusic.sy$daftPunk.GeneratedatFeb10,201205:41:48PMPST\",\"type\":\"record\",\"meta\":\"dbFieldName=music.sy$daft_punk_songs;pk=getLucky;\",\"namespace\":\"com.linkedin.events.anet\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldType=NUMBER;dbFieldPosition=0;\"},{\"name\":\"getLucky\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=GET_LUCKY;dbFieldType=NUMBER;dbFieldPosition=1;\"},{\"name\":\"settings\",\"type\":[{\"name\":\"SETTINGS_T\",\"type\":\"record\",\"fields\":[{\"name\":\"settings\",\"type\":{\"items\":{\"name\":\"settingT\",\"type\":\"record\",\"meta\":\"dbFieldName=SETTINGS;dbFieldType=STRUCT;dbFieldPosition=0;\",\"fields\":[{\"name\":\"instantCrush\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=INSTANT_CRUSH;dbFieldType=NUMBER;dbFieldPosition=0;\"},{\"name\":\"oneMoreTime\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ONE_MORE_TIME;dbFieldType=NUMBER;dbFieldPosition=1;\"},{\"name\":\"somethingAboutUs\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=SOMETHING_ABOUT_US;dbFieldType=VARCHAR;dbFieldPosition=2;\"},{\"name\":\"daFunk\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DA_FUNK;dbFieldType=NUMBER;dbFieldPosition=3;\"},{\"name\":\"robotRock\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ROBOT_ROCK;dbFieldType=NUMBER;dbFieldPosition=4;\"}]},\"name\":\"settingsArray\",\"type\":\"array\"}}]},\"null\"],\"meta\":\"dbFieldName=SETTINGS;dbFieldType=STRUCT;dbFieldPosition=17;\"},{\"name\":\"contact\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CONTACT;dbFieldType=VARCHAR;dbFieldPosition=18;\"},{\"name\":\"digitalLove\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DIGITAL_LOVE;dbFieldType=TIMESTAMP;dbFieldPosition=19;\"},{\"name\":\"humanAfterAll\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=HUMAN_AFTER_ALL;dbFieldType=VARCHAR;dbFieldPosition=20;\"}]}");
  public static final Schema COMPLEX_SCHEMA = Schema.parse("{\"type\":\"record\",\"name\":\"BIG_CITIES_V12\",\"namespace\":\"com.linkedin.events.cities\",\"fields\":[{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldType=NUMBER;dbFieldPosition=1;\"},{\"name\":\"tokyo\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=TOKYO;dbFieldType=CHAR;dbFieldPosition=32;\"},{\"name\":\"delhi\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DELHI;dbFieldType=CHAR;dbFieldPosition=33;\"},{\"name\":\"geo\",\"type\":{\"type\":\"record\",\"name\":\"DATABUS_GEO_T\",\"fields\":[{\"name\":\"country\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=COUNTRY;dbFieldType=VARCHAR;dbFieldType=CHAR;dbFieldPosition=0;\"},{\"name\":\"geoPlaceMaskCode\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=GEO_PLACE_MASK_CODE;dbFieldType=CHAR;dbFieldPosition=5;\"},{\"name\":\"latitudeDeg\",\"type\":[\"float\",\"null\"],\"meta\":\"dbFieldName=LATITUDE_DEG;dbFieldType=NUMBER;dbFieldPosition=6;\"},{\"name\":\"longitudeDeg\",\"type\":[\"float\",\"null\"],\"meta\":\"dbFieldName=LONGITUDE_DEG;dbFieldType=NUMBER;dbFieldPosition=7;\"}]},\"meta\":\"dbFieldName=GEO;dbFieldPosition=34;dbFieldType=DATABUS_GEO_T;\"},{\"name\":\"mexicoCity\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=MEXICO_CITY;dbFieldType=CHAR;dbFieldPosition=41;\"},{\"name\":\"smallerCities\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"smallCityT\",\"fields\":[{\"name\":\"cityId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CITY_ID;dbFieldType=NUMBER;dbFieldPosition=0;\"},{\"name\":\"cityName\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CITY_NAME;dbFieldType=VARCHAR2;dbFieldPosition=1;\"}],\"meta\":\"dbFieldName=SMALLER_CITIES;dbFieldType=ARRAY;dbFieldPosition=42;\"}}},{\"name\":\"osaka\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=OSAKA;dbFieldType=CHAR;dbFieldPosition=43;\"},{\"name\":\"newYork\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=NEW_YORK;dbFieldType=NUMBER;dbFieldPosition=74;\"}],\"meta\":\"dbFieldName=sy$BIG_CITIES;\"}");
  //CHECKSTYLE:ON
}
